import {
  WeatherCloudFogIcon,
  WeatherCloudIcon,
  WeatherCloudLightningIcon,
  WeatherCloudSnowIcon,
  WeatherCloudSunIcon,
  WeatherMiseIcon,
  WeatherMoonIcon,
  WeatherRainIcon,
  WeatherRainbowIcon,
  WeatherSandWindIcon,
  WeatherSnowIcon,
  WeatherSunIcon,
  WeatherSunsetIcon,
  WeatherTyphoonIcon,
  WeatherUmbrellaIcon,
  WeatherWindIcon,
} from '@/icons'

const Weathers = [
  {
    weatherKind: '맑음',
    title: 'Sunny',
    img: '/images/weather/sun.png',
    backgroundColor: '#E5D8BF',
    textColor: '#1A1A1A',
    icon: WeatherSunIcon,
  },
  {
    weatherKind: '구름',
    title: 'Overcast',
    img: '/images/weather/cloud.png',
    backgroundColor: '#4DC684',
    textColor: '#1A1A1A',
    icon: WeatherCloudIcon,
  },
  {
    weatherKind: '흐림',
    title: 'Cloudy',
    img: '/images/weather/cloud-sun.png',
    backgroundColor: '#CACAE7',
    textColor: '#1A1A1A',
    icon: WeatherCloudSunIcon,
  },
  {
    weatherKind: '소나기',
    title: 'Rain',
    img: '/images/weather/rain.png',
    backgroundColor: '#BD8DFB',
    textColor: '#1A1A1A',
    icon: WeatherRainIcon,
  },
  {
    weatherKind: '쨍쨍',
    title: 'Sunset',
    img: '/images/weather/sunset.png',
    backgroundColor: '#CAE5B9',
    textColor: '#1A1A1A',
    icon: WeatherSunsetIcon,
  },
  {
    weatherKind: '가랑눈',
    title: 'Snow',
    img: '/images/weather/cloud-snow.png',
    backgroundColor: '#6BD3DA',
    textColor: '#1A1A1A',
    icon: WeatherCloudSnowIcon,
  },
  {
    weatherKind: '번개',
    title: 'Lightning',
    img: '/images/weather/cloud-lightning.png',
    backgroundColor: '#FF8227',
    textColor: '#1A1A1A',
    icon: WeatherCloudLightningIcon,
  },
  {
    weatherKind: '미풍',
    title: 'Wind',
    img: '/images/weather/wind.png',
    backgroundColor: '#F1A3C4',
    textColor: '#1A1A1A',
    icon: WeatherWindIcon,
  },
  {
    weatherKind: '함박눈',
    title: 'Snowflakes',
    img: '/images/weather/snow.png',
    backgroundColor: '#7875EB',
    textColor: '#1A1A1A',
    icon: WeatherSnowIcon,
  },
  {
    weatherKind: '안개',
    title: 'Fog',
    img: '/images/weather/fog.png',
    backgroundColor: '#5B5F5C',
    textColor: '#FFFFFF',
    icon: WeatherCloudFogIcon,
  },
  {
    weatherKind: '무지개',
    title: 'Rainbow',
    img: '/images/weather/rainbow.png',
    backgroundColor: '#FFCCBC',
    textColor: '#1A1A1A',
    icon: WeatherRainbowIcon,
  },
  {
    weatherKind: '폭우',
    title: 'Heavy Rain',
    img: '/images/weather/umbrella.png',
    backgroundColor: '#2F498D',
    textColor: '#FFFFFF',
    icon: WeatherUmbrellaIcon,
  },
  {
    weatherKind: '달빛',
    title: 'Moon',
    img: '/images/weather/moon.png',
    backgroundColor: '#6D6190',
    textColor: '#FFFFFF',
    icon: WeatherMoonIcon,
  },
  {
    weatherKind: '황사',
    title: 'Sand',
    img: '/images/weather/sand-wind.png',
    backgroundColor: '#D5BFA6',
    textColor: '#1A1A1A',
    icon: WeatherSandWindIcon,
  },
  {
    weatherKind: '미세먼지',
    title: 'Mise',
    img: '/images/weather/mise.png',
    backgroundColor: '#C5C5C5',
    textColor: '#1A1A1A',
    icon: WeatherMiseIcon,
  },
  {
    weatherKind: '태풍',
    title: 'Typhoon',
    img: '/images/weather/typhoon.png',
    backgroundColor: '#1C3BDE',
    textColor: '#FFFFFF',
    icon: WeatherTyphoonIcon,
  },
]

export default Weathers
